#!/bin/bash
# if your program creates an output file (e.g., output.txt) compare it to the file created just now and store the difference in diff.log
#diff result.txt ${APP_DIR}/result.txt > diff.log
touch diff.log 
# comparing stdout generated by your program
diff -B --side-by-side --suppress-common-lines -W 1024 <(sed 's/:::Injecting.*::://g' stdout.txt) ${APP_DIR}/golden_stdout.txt > stdout_diff.log
# comparing stderr generated by your program
diff stderr.txt ${APP_DIR}/golden_stderr.txt > stderr_diff.log
# Application specific output: The following check will be performed only if at least one of diff.log, stdout_diff.log, and stderr_diff.log is different
#diff selected_output.txt selected_golden_output.txt > special_check.log

if [ -s stdout_diff.log ]
then
  ACCEPT=1
  while read line
  do
#    echo "New diff line: $line"
    string=`echo $line | tr "|" " "`
    IFS=' ' read -ra FEATURES <<< "$string"
    if [[ ${FEATURES[0]} != "0:" ]] && [[ ${FEATURES[0]} != "1:" ]] && [[
      ${FEATURES[0]} != "2:" ]] && [[ ${FEATURES[0]} != "3:" ]] && [[
     ${FEATURES[0]} != "4:"} ]];
    then
#      echo "first item is ${FEATURES[0]}, thus.. Continuing"
      continue
    fi
    for i in {1..34}
    do
      j=$i+35
      if [[ ${FEATURES[$i]} == 0.00 ]]
      then
        rate=`echo "scale=10;((${FEATURES[$j]}/1)*100)" | bc`
      else
        rate=`echo "scale=10;(((${FEATURES[$i]}-${FEATURES[$j]})/${FEATURES[$i]})*100)" | bc`
      fi
      value_pos=`echo "$rate < 0" | bc`
      if [ $value_pos = "1" ]
      then
        rate=`echo "-($rate)" | bc`
      fi
      acceptable=`echo "$rate<=2" | bc`
#      echo "i=$i, j=$j, comparing ${FEATURES[$i]} and ${FEATURES[$j]}, rate=$rate"

      if [ $acceptable = "0" ]
      then
 #       echo "NOT ACCEPTABLE"
        ACCEPT=0
        break 2
      fi
    done
  done < stdout_diff.log
  if [ $ACCEPT = 1 ]; then
    cp stdout_diff.log special_check.log
  fi
fi
