#!/bin/bash
# if your program creates an output file (e.g., output.txt) compare it to the file created just now and store the difference in diff.log

#Hotspot output has 26144 lines, if more than 2% of these lines are incorrect
# then output is not tolerable SDC output different
diff --side-by-side --suppress-common-lines ${APP_DIR}/output.out output.out > diff.log
if [ -s diff.log ]
then
  ACCEPT=1
  while read line
  do
    #echo "New line: $line"
    string=`echo $line | tr "|" " "`
    #echo "New string: $string"
    IFS=' ' read -ra OUTPUT_LINE <<< "$string"
    if [[ ${OUTPUT_LINE[3]} == *"e"* ]]
    then
      output_line3=0 #`echo ${OUTPUT_LINE[3]} | sed -e 's/[eE]+*/\\*10\\^/'`
    else
      output_line3=${OUTPUT_LINE[3]}
    fi
    rate=`echo "scale=6; (((${OUTPUT_LINE[1]}-$output_line3)/${OUTPUT_LINE[1]})*100)" | bc`
    
    value_pos=`echo "$rate < 0" | bc`
    #echo "Rate is $rate and Value_pos is $value_pos"
    if [ $value_pos = "1" ]
    then
      #echo "Rate is negative"
      rate=`echo "-($rate)" | bc`
    fi

    acceptable=`echo "$rate<=2" | bc`
    if [ $acceptable = "0" ]
    then
      #echo "We cannot accept"
      ACCEPT=0
      break
    fi
  done < diff.log
  if [ $ACCEPT = 1 ]; then
    cp diff.log special_check.log
  fi
fi

# comparing stdout generated by your program
#diff  <(sed 's/:::Injecting.*::://g' stdout.txt) ${APP_DIR}/golden_stdout.txt > stdout_diff.log
touch stdout_diff.log
# comparing stderr generated by your program
diff stderr.txt ${APP_DIR}/golden_stderr.txt > stderr_diff.log
# Application specific output: The following check will be performed only if at least one of diff.log, stdout_diff.log, and stderr_diff.log is different
#grep "Checking computed" stdout.txt > selected_output.txt 
#grep "Checking computed" ${APP_DIR}/golden_stdout.txt > selected_golden_output.txt 
#diff selected_output.txt selected_golden_output.txt > special_check.log
