#!/bin/bash
# if your program creates an output file (e.g., output.txt) compare it to the file created just now and store the difference in diff.log

#Hotspot output has 26144 lines, if more than 2% of these lines are incorrect
# then output is not tolerable SDC output different
diff  ${APP_DIR}/result.txt result.txt > diff.log
if [ -s diff.log ]
then
  echo "Difference in result.txts" 
  ACCEPT=1
  #echo "New line: $line"
  gold_string=`sed '2q;d' ${APP_DIR}/result.txt`
  string=`sed '2q;d' result.txt`
  #echo "New string: $string"
  IFS=' ' read -ra GOLD_LINE <<< "$gold_string"
  IFS=' ' read -ra OUTPUT_LINE <<< "$string"
  gold_length=`echo ${#GOLD_LINE[@]}`
  output_length=`echo ${#OUTPUT_LINE[@]}`
  echo "gold lengths: $gold_length and out length: $output_length"
  if [[ $gold_length != $output_length ]]
  then
    ACCEPT=0
    #exit 0
  else
    for i in `seq 0 $gold_length`
    do
      if [[ ${OUTPUT_LINE[$i]} == *"e"* ]]
      then
        output_line=0 #`echo ${OUTPUT_LINE[3]} | sed -e 's/[eE]+*/\\*10\\^/'`
      else
        output_line=${OUTPUT_LINE[$i]}
      fi
      if [[ ${GOLD_LINE[$i]} == ${OUTPUT_LINE[$i]} ]]
      then
        i=$i+1
        continue
      fi 
      #echo "Computing ... scale=6; (((${OUTPUT_LINE[$i]}-$output_line)/${OUTPUT_LINE[$i]})*100)" 
      rate=`echo "scale=6; ((((${GOLD_LINE[$i]})-($output_line))/${GOLD_LINE[$i]})*100)" | bc`
      value_pos=`echo "$rate < 0" | bc`
      if [[ $rate != 0 ]]
      then
        echo "Rate is $rate and Value_pos is $value_pos"
      fi
      if [ $value_pos = "1" ]
      then
        echo "Rate is negative"
        rate=`echo "-($rate)" | bc`
      fi
      acceptable=`echo "$rate<=2" | bc`
      if [ $acceptable = "0" ]
      then
        echo "We cannot accept"
        ACCEPT=0
        break
      fi
      i=$i+1
    done
  fi
  if [ $ACCEPT = 1 ]; then
    cp diff.log special_check.log
  fi
fi

# comparing stdout generated by your program
diff  <(sed 's/:::Injecting.*::://g' stdout.txt) ${APP_DIR}/golden_stdout.txt > stdout_diff.log
# comparing stderr generated by your program
diff stderr.txt ${APP_DIR}/golden_stderr.txt > stderr_diff.log
# Application specific output: The following check will be performed only if at least one of diff.log, stdout_diff.log, and stderr_diff.log is different
#grep "Checking computed" stdout.txt > selected_output.txt 
#grep "Checking computed" ${APP_DIR}/golden_stdout.txt > selected_golden_output.txt 
#diff selected_output.txt selected_golden_output.txt > special_check.log
